name: remove-resources

on:
  push:
    branches: [ segraef/azremove ]
    paths:
    - '.github/workflows/remove-resources.yml'

jobs:
  remove:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: azlogin
      uses: ./.github/actions/azlogin
      with:
        identity: 'true'

    - name: 'Remove resource group: rg-3rdparty-hub-govaz-001'
      if: 'true'
      uses: ./.github/actions/azremove
      with:
        resourcegroupName: 'rg-3rdparty-hub-govaz-001'

    - name: 'Remove resource group: rg-infra-csedevtest-govaz-001'
      if: 'false'
      uses: ./.github/actions/azremove
      with:
        resourcegroupName: 'rg-infra-csedevtest-govaz-001'

    - name: 'Remove resource group: rg-infrastructure-hub-govaz-001'
      if: 'true'
      uses: ./.github/actions/azremove
      with:
        resourcegroupName: 'rg-infrastructure-hub-govaz-001'

    - name: 'Remove resource group: rg-network-csedevtest-govaz-001'
      if: 'false'
      uses: ./.github/actions/azremove
      with:
        resourceId: '/subscriptions/47a5904b-f5d7-4a6f-b76b-8b45cd8a9295/resourceGroups/rg-network-csedevtest-govaz-001'

    - name: 'Remove resource: ddos-hub-govaz-001'
      if: 'false'
      uses: ./.github/actions/azremove
      with:
        resourcegroupName: 'rg-network-hub-govaz-001'
        resourceName: 'ddos-hub-govaz-001'
