name: rg-3rdparty-hub-govaz-001

on:
  push:
    branches: [ NotTrigger ]
    paths:
    - '.github/workflows/rg-3rdparty-hub-govaz-001.yml'
    - '.github/workflows/rg-3rdparty-hub-govaz-001/*/*'

env:
  resourceGroupName: 'rg-3rdparty-hub-govaz-001'
  location: 'uswest2'

jobs:
  deploy:
    runs-on: self-hosted 
    steps:
    - uses: actions/checkout@v2
    - name: azlogin
      uses: ./.github/actions/azlogin
      with:
        identity: 'true'
#        environmentName: 'AzureUSGovernment' 
#        subscriptionId: '47a5904b-f5d7-4a6f-b76b-8b45cd8a9295'
#        accountId: 'aac3a4bf-cfbc-466a-7efa-18d514ac9c88' # This is the ClientID for 'mi-github-hub-001'

    - name: 'Virtual Machines: RedHat Identity Manager'
      uses: ./.github/actions/azdeploy
      with:
        resourceGroupName: ${{ env.resourceGroupName }}
        location: ${{ env.location }}
        templateFile: 'Modules/ARM/VirtualMachines/2020-03-12/deploy.json'
        parametersFile: './.github/workflows/${{ env.resourceGroupName }}/VirtualMachines/redHat-IdM.json'   
        
    - name: 'VirtualMachines: RedHat Satellite'
      uses: ./.github/actions/azdeploy
      with:
        resourceGroupName: ${{ env.resourceGroupName }}
        location: ${{ env.location }}
        templateFile: 'Modules/ARM/VirtualMachines/2020-03-12/deploy.json'
        parametersFile: './.github/workflows/${{ env.resourceGroupName }}/VirtualMachines/redHat-satellite.json'             
        
