name: rg-csedevtest-govaz-001

on:
  push: 
    branches: [ NotTrigger ] 
    paths:
    - '.github/workflows/rg-csedevtest-govaz-001.yml'
    - '.github/workflows/rg-csedevtest-govaz-001/**'

env:
  resourceGroupName: 'rg-csedevtest-govaz-001'
  location: 'uswest2'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: azlogin
      uses: ./.github/actions/azlogin
      with:
        identity: 'true'
  #      environmentName: 'AzureUSGovernment' 
  #      subscriptionId: '47a5904b-f5d7-4a6f-b76b-8b45cd8a9295'
  #      accountId: 'a7133410-0757-489c-b5c8-6e25550af495' # This is the ClientID for 'mi-github-devtest-001'

    - name: 'Virtual Machines: Web'
      uses: ./.github/actions/azdeploy 
      with:
        resourceGroupName: ${{ env.resourceGroupName }}
        location: ${{ env.location }}
        templateFile: 'Modules/ARM/VirtualMachines/2020-03-12/deploy.json'
        parametersFile: './.github/workflows/${{ env.resourceGroupName }}/VirtualMachines/web.json'
        
    - name: 'VirtualMachines: App'
      uses: ./.github/actions/azdeploy 
      with:
        resourceGroupName: ${{ env.resourceGroupName }}
        location: ${{ env.location }}
        templateFile: 'Modules/ARM/VirtualMachines/2020-03-12/deploy.json'
        parametersFile: './.github/workflows/${{ env.resourceGroupName }}/VirtualMachines/app.json'

    - name: 'VirtualMachines: Database'
      uses: ./.github/actions/azdeploy 
      with:
        resourceGroupName: ${{ env.resourceGroupName }}
        location: ${{ env.location }}
        templateFile: 'Modules/ARM/VirtualMachines/2020-03-12/deploy.json'
        parametersFile: './.github/workflows/${{ env.resourceGroupName }}/VirtualMachines/data.json'

    - name: 'VirtualMachines: Utility'
      uses: ./.github/actions/azdeploy 
      with:
        resourceGroupName: ${{ env.resourceGroupName }}
        location: ${{ env.location }}
        templateFile: 'Modules/ARM/VirtualMachines/2020-03-12/deploy.json'
        parametersFile: './.github/workflows/${{ env.resourceGroupName }}/VirtualMachines/utility.json'
